name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Define repo tags by current git repo tag
        shell: bash
        run: |
          git describe --tags --always | sed 's/^/REPO_TAG=/' >> $GITHUB_ENV

      - name: Generate Changelog
        run: echo "# Good things have arrived" > $REPO_TAG-CHANGELOG.txt

      - name: "Create release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub release create -a $REPO_TAG-CHANGELOG.txt --draft "${REPO_TAG}"
