---
name: Package images
on: push
jobs:
  sync-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Expand disk free space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/hostedtoolcache /usr/local/lib/android

      - name: Run docker registry
        run: |
          sudo docker run -d --name registry -v /var/lib/registry:/var/lib/registry -p 127.0.0.1:80:5000 registry:2

      - name: Sync images
        shell: bash
        run: |
          bash sync.sh images.list docker.io localhost

      - name: Build skopeo
        shell: bash
        env:
          SKOPEO_VERSION: v1.2.0
        run: |
          docker build -t skopeo:${SKOPEO_VERSION} -f build/Dockerfile.skopeo .
          docker run -d --name skopeo skopeo:${SKOPEO_VERSION} sleep 60s
          docker cp skopeo:/usr/bin/skopeo .

      - name: Build registry images
        shell: bash
        env:
          IMAGE_REPO: "webpsh"
          IMAGE_NAME: "images"
          IMAGE_TAG: "latest"
        run: |
          sudo docker stop registry
          sudo mv -f /var/lib/registry/docker .
          sudo docker build -t ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG} -f build/Dockerfile .
          docker images

      - name: Push image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
